apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: busybox
  namespace: default
spec:
 interval: 1m
 chart:
  spec:
    chart: busybox
    version: 0.1.2
    sourceRef:
      kind: HelmRepository
      name: myhelmrepo
      namespace: default
    interval: 1m