apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.10.1'
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: default
      interval: 1m